### ISSUE TITLE
Volume bleeds on setSize()

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/tomo_raycaster2#11]
whenever we change the size, the volume bleeds. 
![screenshot from 2015-11-27 13 30 16](https://cloud.githubusercontent.com/assets/2225781/11441349/b0090b86-950b-11e5-82f4-ed6b2fde4e73.png)

This is due to upscaling and downscaling of texture map in GPU. I'm not exactly sure what's going on inside. But this seems to be the case. What I found out is GPU does a bilinear filtering on the texture.

One way to solve this is to add extra process to correct the cube edge in shader.

As long as this is not solve, setRenderSize() method is only for debugging purposes and not intended for production.

**Comment by AIRTucha** [comment]
It should not be related with upscaling and downscaling, because we can initially start with any rendering size and it would be ok. I think the best idea is to restart entire engine to change the render size, because it works well.

I don't know about Three.js, but original webGL library allows to set different scaling algorithm. Cube edge or bicubic are to complex for the calculation, common solution is to pre calculate, several maps during initialisation and interpolate between them via other algorithms. The solution is called Mipmaps it is build in to the WebGL, you can get more detailed information here: http://learningwebgl.com/blog/?p=571

**Comment by nicolaisi** [comment]
but we set mipmap generation to false.
https://github.com/kit-ipe/tomo_raycaster2/blob/master/src/core.js#L277

So I assume that no mipmaps are generated.

**Comment by AIRTucha** [comment]
why? it is the best solution, isn't it?

**Comment by nicolaisi** [comment]
Well, we need to understand what is going on at least. Whether it's the WebGL implementation? ThreeJS? Or is it a bug cause by us?

**Comment by AIRTucha** [comment]
sorry for a long response, I did not get, why mipmaps are disabled, it should be best solution for scaling of texture maps.

**Comment by AIRTucha** [comment]
sorry for a long response, I did not get, why mipmaps are disabled, it should be best solution for scaling of texture maps.

**Comment by nicolaisi** [comment]
Not really fixed, but remove setRenderSize. Seems like this implementation is so faulty, that I don't know where to start with. Currently removed this function and if we need this, we can implement it the bug-free way.

9dd25adc772d60df103ffb5d91e43c9ad6e6b710
