### ISSUE TITLE
Anti-aliasing

### ISSUE THREAD

**Issue by nicolaisi** [kit-ipe/tomo_raycaster2#3]
So far the rendered volume suffers from aliasing effect.

1. we will need to implement super-sampling method to remove the jagged edges.
2. implement a stochastic random rays to remove moire effect
3. implement other AA filter such as morphology filter, etc.

**Comment by sogimu** [comment]
What we first should try it, avoid "gluting" of groups of pixels to one big voxel. 
It happens because rounding in function getVolumeValue in secondPass fragment shader:
src/shaders/secondPass.frag

Now invoking getVolumeValue for point with position not fitted to any real pixel on the slicemap, function return value of nearest pixel on the slicemap
